# Configure Prompt
export PS1="
%B%U%n%u%b on %m via %y
[%D{%m/%d/%Y %I:%M:%S %p}] %B%U%~%u%b
%!: %# "
export MYPS1=$PS1

export CLICOLOR=TRUE
export VISUAL=vim

# Configure ZSH History
export HISTFILE=~/.zsh_history
export HISTSIZE=200000
export SAVEHIST=100000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FCNTL_LOCK
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY

# Setup Dev environment
export DEFAULT_PYTHON_VERSION=2.7

export DEFAULT_SYSTEM_PYTHON_PREFIX=/Library/Frameworks/Python.framework/Versions/${DEFAULT_PYTHON_VERSION}
export DEFAULT_USER_PYTHON_PREFIX=~/Library/Python/${DEFAULT_PYTHON_VERSION}

export DEFAULT_SYSTEM_PYTHON_BIN_PATH=${DEFAULT_SYSTEM_PYTHON_PREFIX}/bin
export DEFAULT_USER_PYTHON_BIN_PATH=${DEFAULT_USER_PYTHON_PREFIX}/bin

export DEFAULT_USER_PYTHON_SITE_PACKAGES=${DEFAULT_USER_PYTHON_PREFIX}/lib/python${DEFAULT_PYTHON_VERSION}/site-packages

export PATH=~/bin:${DEFAULT_USER_PYTHON_BIN_PATH}:${DEFAULT_SYSTEM_PYTHON_BIN_PATH}:/usr/local/bin:${PATH}

export MYPYTHONPATH=${DEFAULT_USER_PYTHON_SITE_PACKAGES}
export PYTHONPATH=$MYPYTHONPATH

alias pip_install_local='pip install --install-option="--prefix=${DEFAULT_USER_PYTHON_PREFIX}"'

alias mkvirtualenv='mkvirtualenv --system-site-packages'

export JYTHON_HOME=/usr/local/Cellar/jython/2.5.3/libexec
