# Configure Prompt
export PS1="
%B%U%n%u%b on %m via %y
[%D{%m/%d/%Y %I:%M:%S %p}] %B%U%~%u%b
%!: %# "

export CLICOLOR=TRUE
export VISUAL=vim

# Configure ZSH History
export HISTFILE=~/.zsh_history
export HISTSIZE=200000
export SAVEHIST=100000

setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_FCNTL_LOCK
setopt HIST_FIND_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY

# Setup Dev environment
alias virtualenv='virtualenv --system-site-packages'
alias easy_install='easy_install --user'

export JYTHON_HOME=/usr/local/Cellar/jython/2.5.3/libexec
