
source /usr/local/opt/autoenv/activate.sh

export VIRTUAL_ENV_ROOT=~/work/virtualenvs
export PROJECT_ROOT=~/work/projects

source vexwrapper.zsh

# Fixup terminal
stty erase ^H
case $TERM in
    xterm*)
        precmd () {print -Pn "\e]0;%n@%m: %~\a"}
        ;;
esac

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
